### ISSUE TITLE
Why we need to change App Transport Security settings?

### ISSUE THREAD

**Issue by ifau** [WE-St0r/SwiftyVK#1]
Readme.md says that we need to add exception for vk.com domain:

> For **iOS 9+** and **OSX 10.11+** you need change "App Transport Security" settings on **info.plist** target file.

> ```HTML
<key>NSAppTransportSecurity</key>
<dict>
    <key>NSExceptionDomains</key>
    <dict>
        <key>vk.com</key>
        <dict>
            <key>NSExceptionRequiresForwardSecrecy</key>
            <false/>
            <key>NSIncludesSubdomains</key>
            <true/>
            <key>NSExceptionAllowsInsecureHTTPLoads</key>
            <true/>
        </dict>
    </dict>
</dict>
```

But vk.com api works through https. And it also allows to return links for media with https. From [documentation](https://vk.com/dev/api_requests):

> **Parameters transmissiton in API**
>
> **https – 1** – allows to get **https** links for photos and other media. **0** – methods return **http** links (default). Keep in mind that this parameter works only if you send requests to API through **https**. 

So, what the reason why need to do this?

**Comment by WE-St0r** [comment]
SwiftyVK works over https by default. But there were problems with sending files without this exception. I probably missed this piece of documentation. If has been successfully upload files with https - 1, then there is no need. I'll check.

**Comment by WE-St0r** [comment]
It works in SwiftyVK 1.0.1. Thanks!
