### ISSUE TITLE
Parameters in server answer with authorization method

### ISSUE THREAD

**Issue by AntiPavel** [WE-St0r/SwiftyVK#10]
the only way to get the user email  the params in server response, how to catch it in SwiftyVK?
привет! единственная  возможность получить email пользователя это взять его из ответа сервера на запрос авторизации, если используешь в scope запрос на доступ "email" как добраться до этого ответа в  SwiftyVK ?

**Comment by WE-St0r** [comment]
В SwiftyVK 1.2 параметры токена отдаются в метод vkDidAutorize в ввиде словаря.

**Comment by AntiPavel** [comment]
привет! спасибо за дополнение!
напоминаю поправить описание там в Import and implementation старый метод vkDidAutorize
