### ISSUE TITLE
How to get token after authorization process?

### ISSUE THREAD

**Issue by orkhanalizade** [WE-St0r/SwiftyVK#12]
Hi, how can I get token after

    VK.autorize()

or in 

    VK.processURL(url, options: options)

in AppDelegate `openUrl` function. Can you help me with it, please?

**Comment by WE-St0r** [comment]
You can get token from parameters in vkDidAutorize(parameters: Dictionary<String, String>) VKDelegate function.

**Comment by orkhanalizade** [comment]
Thanks!
