### ISSUE TITLE
How can I fix this error when I try to upload my app to AppStore: xcode invalid bundle structure?

### ISSUE THREAD

**Issue by orkhanalizade** [WE-St0r/SwiftyVK#14]
When I'm trying to upload my app, with the SwiftyVK inside of it, to AppStore, on the Verifying Assets process I get the next error:

    xcode invalid bundle structure

I searched a lot, but could not find any solution. Can you help me with it? Why I get such error? I checked  "Copy Bundle Resources", but I do not have any frameworks there. So, I do not know what is the problem

**Comment by WE-St0r** [comment]
The problem is still relevant?

Unfortunately, now I can not upload applications to store and I can not track what is going wrong. If you have any observation - please share them.

**Comment by Xotab4ik** [comment]
> 21 мая 2016 г., в 21:03, Alexey Kudryavtsev <notifications@github.com> написал(а):
> 
> The problem is still relevant?
> 
> Unfortunately, now I can not upload applications to store and I can not track what is going wrong. If you have any observation - please share them.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub <https://github.com/WE-St0r/SwiftyVK/issues/14#issuecomment-220782493>
The problem is solved, it was my fault. Thank you
