### ISSUE TITLE
Не могу установить фреймворк

### ISSUE THREAD

**Issue by thecashit** [WE-St0r/SwiftyVK#15]
Здравствуйте!

Нашел статью о Вашем фреймворке на хабре - делаю вывод, что можно писать по-русски :)

Пытаюсь добавить фреймворк в проект вручную. Перетащил, прописал в Embedded Libraries и Linked Frameworks в настройках проекта.

Компилятор не ругается на "import SwiftyVK"

Но вот на попытку использовать VKDelegate ругается "Use of undeclared type".
Также ругается на любое использование "VK" - "use of unresolved indentifier VK".

Подскажите, пожалуйста, что у меня с руками.

И спасибо за стоящий проект.

**Comment by WE-St0r** [comment]
Какая версия SwiftyVK и Xcode?

**Comment by thecashit** [comment]
SwiftyVK последняя, Xcode 7.3.1
Проблему решил включением всего проекта SwiftyVK в исходный проект.

Теперь все работает ок
