### ISSUE TITLE
-canOpenURL: failed for URL: "vkauthorize://authorize?" - error: "(null)"

### ISSUE THREAD

**Issue by 4ndrey** [WE-St0r/SwiftyVK#17]
Наблюдаю в консоле:
`-canOpenURL: failed for URL: "vkauthorize://authorize?" - error: "(null)"`

Хотя в целом вроде все работает.
В Info.plist ключ `LSApplicationQueriesSchemes` тоже присутствует (все сделал как в readme).

**Comment by WE-St0r** [comment]
Посмотрите тестовое приложение из репозитория. В библиотеке одновременно проверяется открытие двух видов ссылок. Ключа должно быть два, как на этом скриншоте.

<img width="1012" alt="screen shot 2016-07-13 at 15 43 38" src="https://cloud.githubusercontent.com/assets/8268115/16803708/9a5be222-4910-11e6-8d5b-d271a4117332.png">

**Comment by 4ndrey** [comment]
ок, спасибо!

**Comment by erdemarslan** [comment]
hi,
i set info.plist like your but i see -canOpenURL: failed for URL: "vkauthorize://authorize?" - error: "(null)" on debug area. Where i wrong?

Second is can we authorize automaticly spesificed username and password?
