### ISSUE TITLE
Авторизация через нативное приложение

### ISSUE THREAD

**Issue by igor-lemon** [WE-St0r/SwiftyVK#18]
Не работает авторизация через нативное приложение. Во время обработки авторизации выбрасывает
`016-08-05 18:05:26.809 VkRem[528:97161] -canOpenURL: failed for URL: "vk505933://" - error: "This app is not allowed to query for scheme vk505933"`

Ни добавление `<key>LSApplicationQueriesSchemes</key> 
	<array> 
	    <string>vk</string> 
	    <string>vk-share</string> 
	    <string>vkauthorize</string>
	</array>`
ни 
`<key>LSApplicationQueriesSchemes</key>
  <array>
    <string>vkauthorize</string>
    <string>vk505933</string>
  </array>`
к результату не приводит. Открывает только WebView

**Comment by WE-St0r** [comment]
Нужно добавлять оба одновременно. Посмотрите тестовое приложение и протестируйте его. Ошибок быть не должно. Но авторизация через приложение часто не работает и на это часто жалуются в официальном sdk. Не рекомендую на нее сильно полагаться.

**Comment by igor-lemon** [comment]
Пробовал. С официальным SDK работает, а на Вашем не хочет.
На тестовом приложении та же проблема, авторизация только через Web.

**Comment by WE-St0r** [comment]
Только что проверил. Все работает. У вас оффициальное приложение не открывается или не проходит авторизация? И что происходит с vksdk?

**Comment by igor-lemon** [comment]
Нашел в примере вот это. 
`<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>vk505933</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>vk505933</string>
			</array>
		</dict>
	</array>`

Т.к. создавал проект с 0, то все делал по документации. При добавлении этих параметров все работает.  Может обновите Readme?

**Comment by WE-St0r** [comment]
Возможно, это не совсем ясно из readme
* Add new URL Type with URL identifier `vkauthorize`
* Add new URL Type with URL identifier `vk$YOUR_APP_ID$` (e.g. vk1234567890)
Говорит именно об этом. Потом уже идет:
* Add app schemas to Info.plist file

**Comment by igor-lemon** [comment]
Да, немного ненаглядно. Вначале указано добавить эти 2 параметра, для типа URL-а, а ниже сразу же пример для LSApplicationQueriesSchemes аттрибута с такими же параметрами. Для новичков, вроде меня, это немного вводит в заблуждение.
