### ISSUE TITLE
View is not in the window hierarchy

### ISSUE THREAD

**Issue by igor-lemon** [WE-St0r/SwiftyVK#19]
2016-08-08 03:33:33.098 ~SwiftyVK~[1530:541311] Warning: Attempt to present <SwiftyVK.WebController: 0x15de7a560> on <UIViewController: 0x15dd47630> whose view is not in the view is not in the window hierarchy.

Воспроизвести можно так:

1. Установить какой либо viewController как Initial controller.
2. После запуска приложения переходим на View где находится наша кнопка для авторизации. 
3. Нажимаем на кнопку. Открывается VK приложение. Отказываемся от предоставления нужных прав. Переходим обратно на вьюху с кнопкой авторизации, пробуем ее нажать и уже она не реагирует, в консоль валится эта ошибка. Для того чтобы заново дать возможность авторизоваться нужно перезапускать приложение.

**Comment by WE-St0r** [comment]
Здравствуйте. Хорошо, я посмотрю в чем дело.

**Comment by WE-St0r** [comment]
Проверил. Ошибка указывает на то, что вебвью авторизации пытается быть показан из контроллера, который на данный момент не показывается на экране.

Скорее всего, в методе VKDeledate vkWillPresentView() Вы отдаете контроллер, который сейчас не активен. В реализации тестового приложения я отдаю rootViewController потому, что других контроллеров там просто нет. Вам же нужно следить, чтоб отдавался именно представленный на данный момент на экране контроллер. 

Если будут еще какие-то проблемы с данной ошибкой - пишите.

**Comment by westk0r** [comment]
Привет, а где метод vkWillPresentView посмотреть? Ошибка повторяется
