### ISSUE TITLE
Деинициализация ViewController

### ISSUE THREAD

**Issue by frooman** [WE-St0r/SwiftyVK#23]
У меня не происходит деинициализация ViewController где формирую и отправляю запросы. Напимер, два VC в NavigationViewController, прописываем не пустой 
deinit{
print("test deinit")
}
Если во втором VC сформировать запрос к API VK, то при возврате к первому VC deinit не вызывается, без вызова все хорошо. Где висит силка strong между Request и Connection в библиотеке.

**Comment by frooman** [comment]
Где-то висит strong ссылка*

**Comment by WE-St0r** [comment]
Здравствуйте. Да, блок держит ссылку на контроллер. Посмотрю, что могло пойти не так, но решение может занять какое-то время. Пока используйте слабые ссылки в блоках.
