### ISSUE TITLE
Unable to get all audios

### ISSUE THREAD

**Issue by yarodevuci** [WE-St0r/SwiftyVK#24]
У меня 265 файлов музыки но почему то получаю только 254 
Если принтую response.count выводит 254. Что не так делаю? Помоги плиз
```
 let getAudios = VK.API.Audio.get()
            getAudios.successBlock = { response in
                self.allAudios.removeAll()
                for data in response["items"] {
                    let audio = Audio(serverData: data.1.object as! [String : AnyObject])
                    self.allAudios.append(audio)
                }
                
            }
            getAudios.errorBlock = {error in print("SwiftyVK: friendsGet fail \n \(error)")}
            getAudios.send()

```

**Comment by WE-St0r** [comment]
Попробуйте сделать тот же запрос тут - https://vk.com/dev/audio.get. Вконтакте может не отдавать, например, записи, которые были заблокированы правообладателем. 

Если API вернул ответ, значит такой ответ пришел от VK. Библиотека ответы не подменяет (:

**Comment by yarodevuci** [comment]
Хорошо, попробую.
Еще такая проблема: когда делаю VK.logout и при следущем логине через VK.login() не заполняя юзернэйм и пароль я могу просто нажать отправить и переходит на экран с полем где идет запрос разрешить. То есть как такого выхода из аккаунта не было. Кукиз я удалял тоже. Что может быть?

**Comment by frooman** [comment]
Куки точно не удалились , было и у меня так. 

Как я чищу: 
let storage = NSHTTPCookieStorage.sharedHTTPCookieStorage()
for cookie in storage.cookies! {
 storage.delete(cookie)
}

**Comment by frooman** [comment]
И забыл ещё строчка :
NSUserDefaults.standartUserDefaults().synchronize()

**Comment by yarodevuci** [comment]
я удалял приложение и ставил обратно и проблема такая же

**Comment by WE-St0r** [comment]
@yarodevuci выход из аккаунта в библиотеке происходит. Токена больше нигде быть не должно, но так как авторизация идет через вебью, то сохраняются куки залогиненного пользователя на уровне системы. Чтобы сменить аккаунт, нужно в вебвью выйти из текущего и войти под новым. По крайней мере сейчас это так. В будущем, возможно, что-то придумаю с куками.
