### ISSUE TITLE
VK.API.Audio.search([.searchOwn: "1"]) не возвращает поиск в моих аудио

### ISSUE THREAD

**Issue by yarodevuci** [WE-St0r/SwiftyVK#26]
let getAudios = VK.API.Audio.search([.searchOwn: "1", .q: searchText, .count: "300", .sort: "2", .autoComplete: "1"]) вот что использую
данный запрос не ищет аудио в моих аудиозаписях

**Comment by WE-St0r** [comment]
Здесь с теми же параметрами ищет - https://vk.com/dev/audio.search  ?

**Comment by yarodevuci** [comment]
Неа, значит ошибка API самого вк
