### ISSUE TITLE
частая ошибка авторизации

### ISSUE THREAD

**Issue by yarodevuci** [WE-St0r/SwiftyVK#27]
Делаю запрос, вылетает web view ввожу логин и пароль и жму разрешить и вот что получаю:
 VK.Error VKSDKDomain_(2): User deny authorization
Autorization failed with error: 
VK.Error VKSDKDomain_(2): User deny authorization
в чем ошибка ?

**Comment by WE-St0r** [comment]
Какая платформа?

**Comment by yarodevuci** [comment]
Xcode Version 8.0 (8A218a), iphone 5S 8.4 Simulator

**Comment by yarodevuci** [comment]
![simulator screen shot sep 21 2016 1 27 28 am](https://cloud.githubusercontent.com/assets/13408859/18703414/a2dc4ca0-7f9a-11e6-9cb5-2ce2ac1c9039.png)
еще вот этот глюк всегда выходит с обрезанными кнопками

**Comment by yarodevuci** [comment]
еще вот этот глюк всегда выходит с обрезанными кнопками
![simulator screen shot sep 21 2016 1 27 28 am](https://cloud.githubusercontent.com/assets/13408859/18703529/1077f5fc-7f9b-11e6-82f0-2905a49640ab.png)

**Comment by yarodevuci** [comment]
так что же делать?

**Comment by WE-St0r** [comment]
@yarodevuci, к сожалению, я не смог воспроизвести ваше первую проблему на актуальной версии SwiftyVK. Внутри библиотеки идет парсинг урла в ответе от вк. Данная ошибка авторизации должна происходить только когда он содержит подстроку "access_denied".

Мне нужны дополнительные данные о том, в каком случае происходит ошибка. Как вы пытаетесь авторизоваться, вручную или при получении ошибки от апи о необходимости авторизации? Авторизация через вебвью или vk.app? Какая версия SwiftyVK?

Если можете, пришлите код, вызывающий проблему.

**Comment by yarodevuci** [comment]
@WE-St0r можно с тобой связать через ВК или Скайп?

**Comment by WE-St0r** [comment]
@yarodevuci https://vk.com/we_stor
