### ISSUE TITLE
Не инициируется авторизация через приложение ВК

### ISSUE THREAD

**Issue by Petrachkov** [WE-St0r/SwiftyVK#28]
в классе-авторизаторе есть такой метод:
internal static func recieveTokenURL(url: URL, fromApp app: String?) {
      if (app == "com.vk.vkclient" || app == "com.vk.vkhd" || url.scheme == "vk\(VK.appID)") {
        if url.absoluteString.contains("access_token=") {
          _ = Token(urlString: url.absoluteString)
          WebController.cancel()
        }
      }
    }
так вот url.scheme == "vk\(VK.appID)" выдает "vkOptional(my id)", соответственно никогда не true, если поменять на то, что ниже, то все ок. iOS 10, iPhone 5s, XCode 8, swift 3.

internal static func recieveTokenURL(url: URL, fromApp app: String?) {
		if (app == "com.vk.vkclient" || app == "com.vk.vkhd" || url.scheme == String(format:"vk%@", VK.appID!)) {
        if url.absoluteString.contains("access_token=") {
          _ = Token(urlString: url.absoluteString)
          WebController.cancel()
        }
      }
    }

**Comment by WE-St0r** [comment]
Да, я вижу проблему. Свифт 3 работает с неявно развернутыми опционалльными не так, как в прошлых версиях, а тесты этот кейс не покрывают. Спасибо. Сделаю фикс в ближайшее свободное время.

**Comment by yarodevuci** [comment]
+ 1 тоже заметил этот баг
Xcode 8 и iOS это что то ужасное....

**Comment by WE-St0r** [comment]
@Petrachkov а какую версию SwiftyVK Вы используете? В актуальной (1.3) эта проблема уже была решена.

**Comment by Petrachkov** [comment]
@WE-St0r хм, я просто скачал архивом отсюда с ветки swift3, не через pod'ы, чтобы не заморачиваться + надо было кое-что еще поправить в коде для авторизации.

**Comment by GorbAnthony** [comment]
Походу проблема еще не решена

**Comment by yarodevuci** [comment]
все решено
