### ISSUE TITLE
VK.processURL(url: url, options: options) Вопрос

### ISSUE THREAD

**Issue by yarodevuci** [WE-St0r/SwiftyVK#29]
VK.processURL(url: url, options: options) что делает эта команда? 
и какое решение ее для iOS 8? я так понял VK.processURL_old(url: url, sourceApplication: "") если да, то что должно быть в sourceApplication?

**Comment by WE-St0r** [comment]
Это нужно для авторизации через vk.app, а не вебвью. Протестировать можно только на устройстве с установленным vk.app, не на симуляторе.
Читайте readme в разделе "Authorization with VK App"
