### ISSUE TITLE
Авторизация через приложение 

### ISSUE THREAD

**Issue by yarodevuci** [WE-St0r/SwiftyVK#30]
на iOS 8 авторизация проходит на ура с этой функцией 
func application(_ application: UIApplication, open url: URL, sourceApplication: String?, annotation: Any) -> Bool {
        VK.processURL_old(url: url, sourceApplication: sourceApplication)
        return true
    }

на iOS 9 не хочет... все перепробовал уже. Ставил функцию с README, не помогло. Выбрасывает на авторизованное окно после кнопки разрешить

**Comment by WE-St0r** [comment]
Для 9+ нужно использовать не processURL_old, а processURL.

**Comment by yarodevuci** [comment]
![screen shot 2016-10-06 at 4 16 08 pm](https://cloud.githubusercontent.com/assets/13408859/19174184/d6463f30-8be1-11e6-9cb8-e24dfacb16d6.png)

**Comment by WE-St0r** [comment]
Пожалуйста, прежде чем задавать вопросы, изучайте документацию и работу с warnings в xcode. 

<img width="1121" alt="2016-10-07 8 05 17" src="https://cloud.githubusercontent.com/assets/8268115/19179347/f808652a-8c64-11e6-8796-0f3a82eaad74.png">

**Comment by yarodevuci** [comment]
Благодарю за ответ!
