### ISSUE TITLE
Фото загружается на сервер, но не выкладывается на стену

### ISSUE THREAD

**Issue by T01iK** [WE-St0r/SwiftyVK#34]
Использую следующий код:
```
let request = VK.API.Upload.Photo.toWall.toUser(shareImageMedia, userId: currentUserID)
request.progressBlock = {done, total in print("SwiftyVK: uploadPhoto progress: \(done) of \(total))")}
request.successBlock = {response in print("SwiftyVK: uploadPhoto success \n \(response)")}
request.errorBlock = {error in print("SwiftyVK: uploadPhoto fail \n \(error)")}
request.send()
```
Фото успешно загружается на сервер, консоль это показывает отлично, можно даже перейти по url и посмотреть, но не выкладывается на стену, как того обещает функция.

**Comment by WE-St0r** [comment]
Потому что функция должна вернуть данные о фото, загруженном для отправки на стену. Чтобы опубликовать фото, нужно прикрепить воспользоваться функцией публикации нового поста и передать туда ид загруженных фоток. Ведь помимо фото, вы можете прикрепить еще кучу разных вложений к посту. Глупо бы было в таком случае отправлять пост только с фото.

**Comment by T01iK** [comment]
Прошу прощения, лопухнулся. Спасибо большое за быстрый ответ!
