### ISSUE TITLE
Objective-C + SwiftyVK = ?

### ISSUE THREAD

**Issue by DarkDirectX** [WE-St0r/SwiftyVK#37]
Can I use SwiftyVK in my Objective-C project? Or its impossible?

**Comment by WE-St0r** [comment]
It's impossible because SwiftyVK uses swift structs, enums and tuples that can not be represented in Objective-C. You can use official VK SDK, it,s written in Objective-C.

**Comment by DarkDirectX** [comment]
I need macOS and iOS support, official SDK supported only iOS. Thanks for fast response.

**Comment by WE-St0r** [comment]
You can write wrapper class in swift and use it from Objective-C.
