### ISSUE TITLE
iOS 8.4 Internet connectivity bug

### ISSUE THREAD

**Issue by yarodevuci** [WE-St0r/SwiftyVK#39]
Если выключить интернет и вызвать метод к примеру VK.API.Audio.get().send( то код проходит в  onSuccess: { response in и сам response  пустой.
В прошлой версии в подобной ситуации срабатывала ошибка и выдавало что то типа нет интернет соединение.

**Comment by WE-St0r** [comment]
На всех платформах при отсутствии интернета возвращается ошибка в error блоке. Она инициализируется в недрах URLSession, отдается библиотеке и выше по до блока ошибки. Success блок же вызывается только если от сервера пришел валидный JSON. Эти два случая взаимоисключающие.

Только что я произвел серию тестов на данный счет и не обнаружил неправильного поведения. Пожалуйста, убедитесь, что другие интернет точно отключен, что другие URL запросы возвращают ошибку о том, что нет интернета и если только  SwiftyVK ведет себя неправильно, напишите сюда, приложив настройки VK.config, если Вы их изменяли.

**Comment by yarodevuci** [comment]
VK.config я не трогал. Даже не вижу смысла зачем. Там все по умолчанию 
<img width="1273" alt="screen shot 2016-11-27 at 11 33 37 pm" src="https://cloud.githubusercontent.com/assets/13408859/20659679/f2e15fbc-b4f9-11e6-87a1-13ed2a0058a2.png">

прилагаю скрин. 
Еще раз повторюсь: Ставлю режим самолета, запускаю приложение которое вылетает с ошибкой. Как видно на скрине брэйкпоинт тригнулся в блоке onSuccess. До этого попадало в блок ошибка и там все нормально было.
