### ISSUE TITLE
Crash with VK.configure

### ISSUE THREAD

**Issue by Victor1506** [WE-St0r/SwiftyVK#42]
Здравствуйте. При вызове метода VK.configure(withAppId: Constants.vkId, delegate: self) у меня вылетает warning: could not load any Objective-C class information. This will significantly reduce the quality of type information available. 
![screen shot 2016-11-24 at 2 12 33 pm](https://cloud.githubusercontent.com/assets/18086712/20598108/204586ba-b250-11e6-969a-dc1ddf901b4e.png)

**Comment by WE-St0r** [comment]
Здравствуйте. Данная ошибка не связана со  SwiftyVK, это предупреждение дебаггера. Но call stack выглядит очень интересно. Пожалуйста, сообщите на какой платформе это происходит, приложите конфигурацию VKDelegate и VK.config если его изменяли. Или же тестовый проект с таким же поведением. Так мне будет проще отследить ошибку.

**Comment by Victor1506** [comment]
Изначально все работало нормально но после подключения Facebook, Google+ и однокласники появился этот краш.
IPhone 5, IOS 10.0.2 
VK.config я не изменял
VKDelegate:
![screen shot 2016-11-25 at 10 51 36 am](https://cloud.githubusercontent.com/assets/18086712/20619445/45090afa-b2fd-11e6-8080-167e1df84021.png)

**Comment by WE-St0r** [comment]
Тогда это очень странно.

@Victor1506 уверены ли Вы, что крэш именно в SwiftyVK? В каком треде происходит крэш, что происходит в других тредах? Не вызываете ли вы авторизацию рекурсивно? Пробовали ли отключить библиотеку? Остается ли этот крэш?

**Comment by Victor1506** [comment]
VK.configure(withAppId: Constants.vkId, delegate: self) вызывается разово при нажатии на кнопку а уже в этом методе, в самом SwiftyVK, рекурсивно вызываются другие методы

**Comment by WE-St0r** [comment]
А можете вставить такую строчку (VK.config. logToConsole = true) до вызова авторизации и показать лог?

**Comment by Victor1506** [comment]
![screen shot 2016-11-27 at 11 01 50 am](https://cloud.githubusercontent.com/assets/18086712/20647012/fbe19712-b490-11e6-8dba-1a09a3b29363.png)

**Comment by Victor1506** [comment]
Добавил LogOut() перед VK.configure и заработало
VK.logOut()
VK.configure(withAppId: Constants.vkId, delegate: self)

**Comment by WE-St0r** [comment]
Хорошо, что заработало, но при логауте стирается токен из всех хранилищ и его нужно получать заново. Необходимость логаута - это неправильно.  Видимо, что-то было не так с токеном или с проверкой на срок годности токена. При ближайшей возможности займусь этим багом.

Скажите пожалуйста, токен получали с бесконечным сроком действия или нет?

**Comment by Victor1506** [comment]
если я вас правильно понял то вы имеете ввиду параметр isOffline класса Token и он возвращает false

**Comment by WE-St0r** [comment]
Спасибо, буду тестить

**Comment by WE-St0r** [comment]
Баг исправил, версию обновил. Можете убрать LogOut(). Теперь он только будет мешать)
