### ISSUE TITLE
Возможность отслеживать статус WebView

### ISSUE THREAD

**Issue by dT231** [WE-St0r/SwiftyVK#44]
Доброго времени суток. Появилась необходимость отслеживать состояние WebView когда он закрылся. Можете добавить?

**Comment by WE-St0r** [comment]
Здравствуйте. Можно ли поинтересоваться, какую задачу Вы хотите этим решить и рассматривали ли Вы альтернативные способы решения?

**Comment by WE-St0r** [comment]
Я пока закрою ваш вопрос, так как не получил ответа. Вы можете открыть его снова, при необходимости.
