### ISSUE TITLE
Models for each content type.

### ISSUE THREAD

**Issue by mokeev1995** [WE-St0r/SwiftyVK#47]
Добрый день. 

Есть предложение сделать для каждого раздела свою модель. Предложение основано на примерах таких библиотек, как https://github.com/virtyaluk/InTouch или https://github.com/vknet/vk

вот тут есть списки моделей:
- https://github.com/vknet/vk/tree/master/VkNet.UWP/Model
- https://github.com/virtyaluk/InTouch/tree/master/ModernDev.InTouch.Shared/Model

**Comment by WE-St0r** [comment]
Здравствуйте. На данный момент я сомневаюсь в целесообразности ручного создания всех моделей и не располагаю временными ресурсами для этого. У вк есть json схема всех ответов апи. Можно было бы воспользоваться автогенерацией моделей по этой схеме, но решений для swift я пока не нашел. Если Вы знаете такое, пожалуйста сообщите.

**Comment by mokeev1995** [comment]
Могу помочь с воссозданием всех моделек, вопрос в инфраструктуре. в лямбды-колбэки должны приходить эти модельки) стоит попробовать?

**Comment by WE-St0r** [comment]
В калбеки они определенно не должны приходить, так как ответ от сервера может быть с достаточно сложной структурой. Если мы будем пытаться всегда привести ответ к каким-то моделям, то можем потерять некоторые данные, особенно одиночные значения в корне JSON.

Я сомневаюсь в необходимости добавлять слой моделей в библиотеку, так как в первую очередь она призвана выполнять роль прослойки для удобного вызова методов API вконтакте. Реализация же моделей выходит за рамки решаемой SwiftyVK задачи.

Я вижу много потенциальных минусов в таком решении. Вот некоторые из них:

Разработчик может хотеть использовать в качестве модели структуру, Swift-класс, класс-наследник NSObject,  NSManagedObject или какой-то свой вариант. У каждого решения есть свои преимущества и недостатки. Сделать одну реализацию для всех нуждающихся, к сожалению, не выйдет. 

Реализация моделей в библиотеке может просто не вписываться в архитектуру приложения.

Целый набор моделей будет излишним потому, что большинство разработчиков используют лишь малую часть типов обьектов VK API и так же далеко не все их поля.

Нужно учитывать проблемы с поддержкой моделей в актуальном состоянии и множеством потенциальных багов в большом обьеме дополнительного кода.

По этим причинам я бы предпочел предоставить выбор реализации разработчику, который будет использовать SwiftyVK  в своем проекте. Таким образом он получит свободу в выборе моделей, а я смогу сконцентрироваться на основном функционале SwiftyVK и на других проектах.

**Comment by mokeev1995** [comment]
хмм.. ну, хорошо) тогда вопрос закрыт)
