### ISSUE TITLE
execute error

### ISSUE THREAD

**Issue by ilyakooo0** [WE-St0r/SwiftyVK#51]
hen sending an execute request through official SDK, everything works normally as expected. When I try to send the exact same code through SwiftyVK it returns `error SwiftyVKApiError[12]: Unable to compile code:  ';' expected, 'chatUsersArrs' found in line 1` 

code(as is in swift):
```swift
        let code = "var fields = [\"id\", \"first_name\", \"last_name\", \"deactivated\", \"about\", \"bdate\", \"blacklisted\", \"blacklisted_by_me\", \"can_send_friend_request\", \"can_write_private_message\", \"common_count\", \"connections\", \"contacts\", \"exports\", \"friend_status\", \"online\", \"photo_max_orig\", \"site\", \"photo_max\", \"last_seen\"];  var dialogs = API.messages.getDialogs({\"offset\": \(offset), \"count\": \(count)}); var userIDs =  dialogs.items@.message@.user_id; var chatIDs = dialogs.items@.message@.chat_id;   var users = API.users.get({\"user_ids\": userIDs, \"fields\": fields}); var chats = API.messages.getChat({\"chat_ids\": chatIDs, \"fields\": fields}); var chatsToReturn = API.messages.getChat({\"chat_ids\": chatIDs, \"fields\": [\"id\"]}); var chatUsersArrs = chats@.users; var chatUsers = []; var i = 0; while (chatUsersArrs[i]) {     chatUsers = chatUsers + chatUsersArrs[i];     i = i + 1; } var chatUserInviters = API.users.get({\"user_ids\": chatUsers@.invited_by, \"fields\": fields}); return [dialogs, users, chatUsers, chatUserInviters, chatsToReturn]; "
```

As normal code:
```javascript
var fields = ["id", "first_name", "last_name", "deactivated", "about", "bdate", "blacklisted", "blacklisted_by_me", "can_send_friend_request", "can_write_private_message", "common_count", "connections", "contacts", "exports", "friend_status", "online", "photo_max_orig", "site", "photo_max", "last_seen"];

var dialogs = API.messages.getDialogs({"offset": 0, "count": 20});
var userIDs =  dialogs.items@.message@.user_id;
var chatIDs = dialogs.items@.message@.chat_id;


var users = API.users.get({"user_ids": userIDs, "fields": fields});
var chats = API.messages.getChat({"chat_ids": chatIDs, "fields": fields});
var chatsToReturn = API.messages.getChat({"chat_ids": chatIDs, "fields": ["id"]});
var chatUsersArrs = chats@.users;
var chatUsers = [];
var i = 0;
while (chatUsersArrs[i]) {
    chatUsers = chatUsers + chatUsersArrs[i];
    i = i + 1;
}
var chatUserInviters = API.users.get({"user_ids": chatUsers@.invited_by, "fields": fields});
return [dialogs, users, chatUsers, chatUserInviters, chatsToReturn];
```

Pretty sure the problem is in how you handle and send the string as similar problems have occurred in the past.

**Comment by WE-St0r** [comment]
I created swift code step-by-step from your normal version

`
let code = "var fields = [\"id\", \"first_name\", \"last_name\", \"deactivated\", \"about\", \"bdate\", \"blacklisted\", \"blacklisted_by_me\", \"can_send_friend_request\", \"can_write_private_message\", \"common_count\", \"connections\", \"contacts\", \"exports\", \"friend_status\", \"online\", \"photo_max_orig\", \"site\", \"photo_max\", \"last_seen\"]; var dialogs = API.messages.getDialogs({\"offset\": 0, \"count\": 20}); var userIDs = dialogs.items@.message@.user_id; var chatIDs = dialogs.items@.message@.chat_id; var users = API.users.get({\"user_ids\": userIDs, \"fields\": fields}); var chats = API.messages.getChat({\"chat_ids\": chatIDs, \"fields\": fields}); var chatsToReturn = API.messages.getChat({\"chat_ids\": chatIDs, \"fields\": [\"id\"]}); var chatUsersArrs = chats@.users; var chatUsers = []; var i = 0; while (chatUsersArrs[i]) { chatUsers = chatUsers + chatUsersArrs[i]; i = i + 1; }; var chatUserInviters = API.users.get({\"user_ids\": chatUsers@.invited_by, \"fields\": fields}); return [dialogs, users, chatUsers, chatUserInviters, chatsToReturn];"
`

It works! :)

**Comment by WE-St0r** [comment]
I prefer to create such requests on the server side and just call them from client

**Comment by ilyakooo0** [comment]
Might be my screw up. 
I ended up storing the function on the server.
