### ISSUE TITLE
Проблема компилровки 

### ISSUE THREAD

**Issue by yarodevuci** [WE-St0r/SwiftyVK#53]
Каждый раз с обновлением приходится копаться в файлах и чистить plist файл
Пофиксай пожалуйста этот баг
![screen shot 2017-01-22 at 5 55 23 pm](https://cloud.githubusercontent.com/assets/13408859/22188650/24a5a442-e0cc-11e6-86bf-25349f0ddd29.png)

**Comment by ilyakooo0** [comment]
А как ты обновляешься?

**Comment by zhaxylykbayev** [comment]
как ты ее решил?

**Comment by yarodevuci** [comment]
@ilyakooo0 через pod update 
@zhaxylykbayev В принципе сделал то что и написано. в SwiftVK в info.plist удалил CFBundleExecutable

У вас такая же проблема?

**Comment by zhaxylykbayev** [comment]
Да, после удаления появилась проблема itms 90171

**Comment by yarodevuci** [comment]
@zhaxylykbayev кинь скрин, возможно ты не совсем то что надо удалил

**Comment by ilyakooo0** [comment]
Я использую Carthage и у меня такой проблемы не было

**Comment by WE-St0r** [comment]
@yarodevuci, судя по документации Apple [здесь](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html) ключ необходим для динамической загрузки библиотеки в рантайме. 

По всем требованиям ключ верный. На всякий случай поменял Bundle ID. Попробуйте подтянуть последний коммит и проверить поведение.
