### ISSUE TITLE
LongPool

### ISSUE THREAD

**Issue by ilyakooo0** [WE-St0r/SwiftyVK#54]
Вы меня простите, но я не выдержал.

Почему `LongPool` то? 
Везде, кроме кода SwiftyVK это `LongPoll`.

Я попытался исправить, но мне не дали. 

Раскроойте тайну, пожалуйста...

**Comment by WE-St0r** [comment]
Извините, моя ошибка. Подумалось, что не смержил коммит с переименованием. Переименовал руками, только, увы, не туда. Вообще, никак не могу запомнить с лонгпулом, как правильно. Всегда кажется, что бассейн - это верно. Я исправлю на выходных, или можете снова сами сделать пр.

**Comment by ilyakooo0** [comment]
лонгпол
