### ISSUE TITLE
Отправка запросов без ограничений SendLimit = false

### ISSUE THREAD

**Issue by frooman** [WE-St0r/SwiftyVK#55]
При выборе любого параметра нормального отключения лимитирования нет , запросы выполняются строго друг за другом , и если идёт upload видео или фото, то останавливается вся работа sdk

**Comment by WE-St0r** [comment]
Спасибо за отзыв. Не тестировал ранее этот случай. Теперь должно работать правильно)

**Comment by frooman** [comment]
Просто использую полностью ваш sdk в полном клиенте ВК. Вам за него спасибо.

**Comment by frooman** [comment]
Еще бы добавил опцию для запросов - выборочная последовательность, иногода полезно количество запросов самому контролировать, а аплоад файлов последовательно. Ну это так прихоть.

**Comment by WE-St0r** [comment]
Не за что. Если будут предложения и пожелания - пишите)
