### ISSUE TITLE
ERROR ITMS-90535

### ISSUE THREAD

**Issue by ben73** [WE-St0r/SwiftyVK#56]
При заливке приложения в Appstore появляется ошибка:

`ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Wizl.app/Frameworks/SwiftyVK.framework/SwiftyVKResources-iOS.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."`

Исправляется способом, указанным в описании ошибки, т.е. надо удалить ключ CFBundleExecutable из SwiftyVKResources-iOS.bundle/Info.plist

Автор, не мог бы ты удалить этот ключ, чтобы не приходилось каждый раз ручками править?

**Comment by WE-St0r** [comment]
Спасибо за обращение. Ключ из ресурсов удалил.
