### ISSUE TITLE
error while uploading to App Store

### ISSUE THREAD

**Issue by PsssUm** [WE-St0r/SwiftyVK#57]
Could you help? I have this error while uploading to App Store .
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Get Likes VK.app/Frameworks/SwiftyVK.framework/SwiftyVKResources-iOS.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/Get Likes VK.app/Frameworks/SwiftyVK.framework/SwiftyVKResources-iOS.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by WE-St0r** [comment]
Please fill issue template in future.
This bug was fixed in latest SwiftyVK version (2.0.6).

**Comment by WE-St0r** [comment]
#56
