### ISSUE TITLE
Таймаут авторизации

### ISSUE THREAD

**Issue by da-manifest** [WE-St0r/SwiftyVK#58]
Добрый день!
Можно ли как-то задать таймаут авторизации? При отключенном интернете приложение зависает на webView авторизации

**Comment by WE-St0r** [comment]
@da-manifest сейчас задать таймаут нельзя, но я посмотрю почему так происходит и что можно сделать.

**Comment by WE-St0r** [comment]
@da-manifest на какой платформе воспроизводится баг? Происходит зависание или падение приложения? 

Пожалуйста, заполняйте issue template

**Comment by da-manifest** [comment]
Приложение зависает(белый экран webView и бесконечно крутится activityIndicator). Проверял на симуляторе на ios 8.1, 9.0, на устройстве iphone 5s c ios 9.3
Приложение падает в симуляторе на ios 10.2, в WebController-ios.swift, в методе func load(url: String), строка 67 
Ошибка: Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

**Comment by WE-St0r** [comment]
@da-manifest проверяйте)

**Comment by da-manifest** [comment]
Спасибо!) Все работает
