### ISSUE TITLE
Как получить данные из асинхронного блока onSuccess?

### ISSUE THREAD

**Issue by smocer** [WE-St0r/SwiftyVK#59]
🚫IMPORTANT! If this template is not filled out your issue **will** be closed with no comment. Please fill template and remove this line.🚫

### New Issue Checklist

* [ +] I have looked at the [README.md](./README.md)
* [+ ] I have looked at the [Example project](./Example)
* [+ ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform               | ios
 Platform Version        | 10.2
  Swift Version          | 3
 SwiftyVK Version        |  2.0.6
 Integration Method     | manually
 
### Issue Description

Есть следующий код:

```
VK.API.Upload.Photo.toWall.toUser(media, userId: userIDForVK).send(
                onSuccess: { response in
                    print("SwiftyVK: uploadPhoto success \n \(response)")},
                onError: { error in
                    print("SwiftyVK: uploadPhoto fail \n \(error)") },
                onProgress: { done, total in
                    print("SwiftyVK: uploadPhoto progress: \(done) of \(total))") }
            )
```
Как мне записать данные из переменной `response` в мою переменную? Вся проблема в том, что блок onSuccess выполняется асинхронно на другом потоке, поэтому если я тупо вписываю в этот блок сразу после `print` строку `myVariable = response[0,"id"].stringValue`, то она остается пустой после выполнения метода `VK.API.Upload.Photo.toWall.toUser.send`. Пока что я сделал "костыль": отредактировал код фреймворка, добавив в функцию parseResponseFrom(data: Data) из файла Source\SDK\Request\Result.swift строку `NotificationCenter.default.post(name: NSNotification.Name(rawValue: "userIDForVK"), object: nil, userInfo: ["userID":json[0,"id"].stringValue])`, при этом в своем файле я буду наблюдать за этим оповещением. Но это плохой способ, можно как то получить этот `response`, не редактируя фреймворк?

**Comment by smocer** [comment]
UPD: костыль с NotificationCenter не работает, удалил его.

**Comment by smocer** [comment]
Внесу больше ясности в свой вопрос:
У меня есть некоторая функция `sendToVK(message: String, photos: [UIImage])`. Опишу в общих чертах ее тело:
```

func sendToVK(message: String, photos: [UIImage]) {
    // описание некоторых переменных
    var attachments = "" // в этой переменной в итоге должна лежать информация обо всех фотографиях, 
//которые я хочу прикрепить к посту, в виде "photo123456_987654,photo123456_612366,photo123456_123156",
// где 123456 - это id юзера, к которому на стену загрузятся фотки (он у меня уже есть),
// а цифры после "_" - это как раз id непосредственно фотографии, 
//который приходит в ответе сервера после успешной загрузки фото

    for photo in photos {
       // в этом цикле загружаю на сервер фотографии, и по идее где то в нем же я должен получать ID фотографии из ответа (response) сервера для дальнейшей работы
      //в этом же цикле выполняется кусок кода, опубликованный в моем самом первом сообщении
      //пусть photoString - это сформированная строка вида "photo12345_612515"

      attachments += photoString
    }

    //тут в wallPostParameters есть все параметры, необходимые для публикации, включая и attachments
    VK.API.Wall.post(wallPostParameters).send(
            onSuccess: {response in print(response)},
            onError: {error in print(error)},
            onProgress: {done, total in print(" !!!!!!!!!!!!!!! send \(done) of \(total)")}
        )
}

```
И сама проблема заключается в том, что в цикле, где я итерирую по фотографиям, задача загрузки на сервер отправляется на другой поток, соответственно, ответ в **photoString**  записывается тоже в другое время "где-то там". И по факту получается, что к моменту, когда мне уже нужны заполненные **attachments** (прямо перед вызовом VK.API.Wall.post), они заполнены _без ID фотографий_, то есть строкой вида "photo123456_,photo123456_,photo123456_", потому что где-то в другом потоке эти фотографии еще не успели загрузиться, и, как следствие, в строку attachments необходимые ID не были добавлены.

Суть вопроса заключается в следующем: как мне реализовать на свифте то, что в цикле при каждой итерации мы не продолжаем выполнение, а ждем загрузки фото, добавляем ее id в **photoString** и накапливаем эти **photoString** в **attachments**, чтобы перед вызовом VK.API.Wall.post все было готово к отправке?

**Comment by WE-St0r** [comment]
Здравствуйте. К сожалению, Ваш вопрос не относится непосредственно к SwiftyVK, а касается такой базовой вещи как многопоточное программирование. Одно из решений - отправлять все запросы загрузки из отдельного потока в котором ждать окончания их выполнения, например, с помощью `dispatchGroup`. После окончания всех запросов массив будет заполнен и готов к отправке. Можно отправить последний запрос из того же кастомного потока.
