### ISSUE TITLE
canOpenURL: failed for URL: "vkauthorize://authorize?" - error: "(null)"

### ISSUE THREAD

**Issue by Matsepura** [WE-St0r/SwiftyVK#6]
canOpenURL: failed for URL: "vkauthorize://authorize?" - error: "(null)"
open login and password, after it, need to show field with sms code, but open log and password view

**Comment by WE-St0r** [comment]
Двухфакторную авторизацию починил.
canOpenURL: failed for URL: "vkauthorize://authorize?" - error: "(null)" - ругается, что не может открыть авторизацию через официальный клиент VK на iOS. Нет VK App  или неверные настройки для авторизации через него. В данном случае показывает  WebView.
