### ISSUE TITLE
Регистрация Push уведомлений

### ISSUE THREAD

**Issue by Amekill** [WE-St0r/SwiftyVK#62]
### New Issue Checklist

* [+] I have looked at the [README.md](./README.md)
* [+] I have looked at the [Example project](./Example)
* [+] I have filled out this issue template.

### Issue Info

 Info                                   | Value                               |
-------------------------|-------------------------------------|
 Platform                           | iOS
 Platform Version             | 10.2
 Swift Version                   | 3.1
 SwiftyVK Version            |  2.0.7
 Integration Method         | carthage
 
### Issue Description

Невозможно зарегистрировать устройство на push уведомления, поскольку отсутствует выбор важных параметров: device_id, sandbox (метод VK.API.Account.registerDevice)

**Comment by WE-St0r** [comment]
Спасибо. Параметры добавлены. В будущем Вы всегда можете добавить любые мелкие правки сделав pull request своих изменений в этот репозиторий)
