### ISSUE TITLE
Get email

### ISSUE THREAD

**Issue by StrelnikovEugene** [WE-St0r/SwiftyVK#63]
### New Issue Checklist

* [x] I have looked at the [README.md](./README.md)
* [x] I have looked at the [Example project](./Example)
* [x] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios/
 Platform Version        | 10.0
  Swift Version          |  3.0
 SwiftyVK Version        | 2.0.8
 Integration Method      | cocoapods
 
### Issue Description

How can I get email of current user?

**Comment by WE-St0r** [comment]
See #10
