### ISSUE TITLE
Авторизация

### ISSUE THREAD

**Issue by Amekill** [WE-St0r/SwiftyVK#65]
### New Issue Checklist

* [+] I have looked at the [README.md](./README.md)
* [+] I have looked at the [Example project](./Example)
* [+] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 10.2.1 / Симулятор 10.3
 Swift Version          | 3.1
 SwiftyVK Version        | 2.0.7
 Integration Method      | carthage
 
### Issue Description

Если авторизоваться, затем удалить приложение и заново его установить, то авторизация проходит автоматически. Как можно такое пофиксить? 
p.s. она сбросится если выйти методом vk.logout или сбросить все настройки + контент iOS

**Comment by WE-St0r** [comment]
Здравствуйте. Это системное поведение для keychain и многих оно может устраивать. Вы можете проверять в приложении, первый ли это запуск и сбрасывать keychain с помощью vk.logout.
