### ISSUE TITLE
Failure compiling on real device 

### ISSUE THREAD

**Issue by Z1napp** [WE-St0r/SwiftyVK#66]
### New Issue Checklist

 [*] I have looked at the [README.md](./README.md)
 [*] I have looked at the [Example project](./Example)
 [*] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | ios
 Platform Version        | 10.3
 Swift Version          |  3.1
 SwiftyVK Version        | last
 Integration Method      | manually
 Xcode version          | Version 8.3 beta 2 (8W120l)
Device | iPhone 6
Version of real device | 10.3.2
### Issue Description

Hello. I have a trouble: my project is run on simulator, but it doesn't on real device. I don't know what can I do with it. When I'll try to launch application on real device - fail reports write me about wrong syntax. For example: "VK", "JSON" etc. I can import module to my project, but I can't use syntax of SwiftyVK library. Likely this trouble not applicable too your library, but I don't know what to do. 

Здравствуйте. У меня проблема: мой проект запускается и компилируется в симуляторе, но не на реальном девайсе. Я не знаю что мне делать с этим. Когда я пытаюсь запустить приложение на реальном девайсе - блок о ошибках говорит мне о неправильности синтаксиса. Например: "VK", "JSON" и так далее. Я могу подключить модуль к своему проекту, но я не могу использовать синтаксис библиотеки SwiftyVK. Скорее всего эта ошибка не относится к вашей библиотеке, но я не знаю что мне делать.

**Comment by WE-St0r** [comment]
Извините, к сожалению, я не могу понять, что именно у Вас пошло не так. Возможно проблема с интеграцией библиотеки в проект. Попробуйте интегрировать ее еще раз. Если проблема не решится - пришлите тестовый проект, в котором она воспроизводится.

**Comment by Z1napp** [comment]
Everything is ok. Trouble was in manual installation of library. I was reinstall it but now with cocoa. Strange mistake…
