### ISSUE TITLE
Questions about user personal data

### ISSUE THREAD

**Issue by adsalpha** [WE-St0r/SwiftyVK#67]
### New Issue Checklist

* [x ] I have looked at the [README.md](./README.md)
* [x ] I have looked at the [Example project](./Example)
* [x ] I have filled out this issue template.

### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                | iOS
 Platform Version        | 10.3
  Swift Version          | Last version available 
 SwiftyVK Version        | Last version available 
 Integration Method      | cocoapods
 
### Issue Description

Questions:
1. Does SwiftyVK provide the capability to get a user's email from the API? What about the full phone number? If yes, how?
2. How do I access the token issued by VK and get the user's ID for manual queries?

**Comment by ilyakooo0** [comment]
You can get the email from vkDidAutorize. It gets passed a dictionary with one of the values being the email address of the user.

**Comment by WE-St0r** [comment]
Yes, you can get email in vkDidAutorize with 'email' auth scope.
You can get phone in users.get method with 'contacts' parameter.
You can get token in vkDidAutorize method.
